#!/bin/bash
username=$(id -u -n 1000)

changeinterface() {
config="/home/$username/.config/polybar/config.ini" # Define polybar config file
eth() {
if=$(ip -br l | awk '$1 !~ "lo|vir|wl|tun" { print $1}') # Find user's eth interface
if [ -z "$if" ];then # is interface empty?
        # If there is no eth interface, do not do anything.
        exit
fi
# Automatically take default interface in the config
grabinterfaces="$(cat $config | grep '^interface =')" # Grab all interfaces in the config
defif="$(echo $grabinterfaces | awk '{print $3}')" # Take default eth interface in the config
sed -i "s/$defif/$if/g" "$config" # change default eth interface to yours
}
wlan() {
if=$(ip -br l | awk '$1 !~ "lo|vir|eth|en|tun" { print $1}') # Find user's wlan interface
if [ -z "$if" ];then # is interface empty?
        # If there is no wlan interface, do not do anything.
        exit
fi
grabinterfaces="$(cat $config |	grep '^interface =')" # Grab all interfaces in the config
defif="$(echo $grabinterfaces | awk '{print $6}')" # Take default wlan interface in the config
sed -i "s/$defif/$if/g" "$config" # change default wlan interface to yours
}
# Run functions
eth
wlan
}
changeinterface
